apiVersion: v1
kind: Service
metadata:
  name: patroni-psql-repl
  labels:
    application: patroni
    cluster-name:  &cluster_name patroni-psql
    role: replica
spec:
  type: ClusterIP
  selector:
    application: patroni
    cluster-name: *cluster_name
    role: replica
  ports:
    - port: 5432
      targetPort: 5433