apiVersion: v1
kind: Service
metadata:
  name: haproxy-admin-svc
  labels:
    app: haproxy
spec:
  type: NodePort
  ports:
    - port: 1000
      targetPort: 1000
      nodePort: 31000
      name: admin-port
  selector:
    app: haproxy